export const FETCH_PROFILES_BEGIN = "FETCH_PROFILES_BEGIN";
export const FETCH_PROFILES_SUCCESS = "FETCH_PROFILES_SUCCESS";
export const FETCH_PROFILES_FAILURE = "FETCH_PROFILES_FAILURE";

export const FETCH_ATTRIBUTES_BEGIN = "FETCH_ATTRIBUTES_BEGIN";
export const FETCH_ATTRIBUTES_SUCCESS = "FETCH_ATTRIBUTES_SUCCESS";
export const FETCH_ATTRIBUTES_FAILURE = "FETCH_ATTRIBUTES_FAILURE";

export const FETCH_PREDICTS_BEGIN = "FETCH_PREDICTS_BEGIN";
export const FETCH_PREDICTS_SUCCESS = "FETCH_PREDICTS_SUCCESS";
export const FETCH_PREDICTS_FAILURE = "FETCH_PREDICTS_FAILURE";

export const SEARCH_PROFILES_BEGIN = "SEARCH_PROFILES_BEGIN";
export const SEARCH_PROFILES_SUCCESS = "SEARCH_PROFILES_SUCCESS";
export const SEARCH_PROFILES_FAILURE = "SEARCH_PROFILES_FAILURE";

